version: '3.8'

services:
  plate-recognition:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./Data:/app/Data:ro  # 唯讀模式掛載輸入資料
      - ./OutPut:/app/OutPut
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - TZ=Asia/Taipei
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s